language: java

services:
  - docker

before_install:
  - chmod +x gradlew
  
jdk:
  - oraclejdk8

script:
  - docker build -t kwonghung/spring-boot-and-docker-secret .
  - docker login --help
  - echo "$DOCKER_HUB_PASSWORD" | docker login --username "$DOCKER_HUB_USERNAME" --password-stdin
  - docker push kwonghung/spring-boot-and-docker-secret
