---
spring:
  profiles: default
  
  datasource:
    url: jdbc:mysql://dockerce01:3306/mysql
    username: root
    password: password

---
spring:
  profiles: docker-stack
  
  datasource:
    url: jdbc:mysql://mysql:3306/testdb
    username: dba
    password: ${docker-secret-mysql-user-pw}
    
docker-secret:
  bind-path: /run/secrets
---
spring:
  profiles: k8s
  
  datasource:
    url: jdbc:mysql://mysql-svc:3306/testdb
    username: testuser
    password: ${docker-secret-mysql-passwd}
    
docker-secret1:
  bind-path: /run/secrets/mysql-secret
