---
spring:
  profiles: default
  
  datasource:    url: jdbc:mysql://dockerce01:3306/mysql
    username: root
    password: password

---
spring:
  profiles: docker-stack
  
  datasource:
    url: jdbc:mysql://mysql:3306/mysql
    username: root
    password: ${docker-secret-mysql-root-pw}
    
docker-secret:
  bind-path: /run/secrets