---
spring:
  profiles: default
  
  datasource:
    url: jdbc:mysql://dockerce01:3306/mysql
    username: root
    password: password

---
spring:
  profiles: docker-stack
  
  datasource:
    url: jdbc:mysql://mysql:3306/testdb
    username: root
    password: password
    #${docker-secret-mysql-user-pw}
    
docker-secret:
  bind-path: /run/secrets
